language: scala
scala:
  - 2.10.6
  - 2.11.8
  - 2.12.1
jdk:
  - openjdk7
  - openjdk8
matrix:
  exclude: # NB: Scala 2.12 requires JDK 8
  - scala: 2.12.1
    jdk: openjdk7
sudo: false
script:
  - sbt test transferPublishAndTagResources
  - scripts/publishAndTag 'slamdata/scala-xml-names'
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
